### ISSUE TITLE
Page Contato 

### ISSUE THREAD

**Issue by leozancheta** [leozancheta/teste#1]
<h1>
I need help to fix the bug on the contact page that is not getting to the right of  LOGO , as well as on the other pages !!
</h1>

**Comment by Senhordim** [comment]
@leozancheta no seu arquivo contato.html na linha que você declara a tag **header** você não passou a propriedade class como nas outras páginas.
`<header class="cabecalho">`
Creio que essa implementação resolva seu problema.
